name: Publish
on: [ push ]
concurrency: ci-${{ github.ref }}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18
      - uses: actions/checkout@v3
        with:
          repository: uten2c/repo
          path: "./repo"
      - uses: gradle/wrapper-validation-action@v1
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}
      - run: chmod +x ./gradlew
      - run: ./gradlew build publish --stacktrace
        env:
          REPO_URL: "./repo"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination-github-username: CI
          source-directory: "./repo"
          commit-message: "${{github.head_ref}}+build.${{ steps.buildnumber.outputs.build_number }}"
          branch: main
