name: Publish
on: [ push ]
concurrency: ci-${{ github.ref }}
permissions: write-all
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}
          prefix: ${{ github.ref }}
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x ./gradlew
      - name: Publish
        run: |
          ./gradlew cloneRepo --stacktrace
          ./gradlew publish --stacktrace
          ./gradlew pushRepo --stacktrace
        env:
          REPO: uten2c/repo
          TOKEN: ${{ secrets.TOKEN }}
          GIT_USER: uTen2c
          GIT_EMAIL: uten2c@gmail.com
